# Generated by Django 3.2.20 on 2023-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230716_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
