# Generated by Django 4.2.4 on 2023-10-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_mydata_gauge_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maskrcnndata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startx", models.FloatField(null=True)),
                ("starty", models.FloatField(null=True)),
                ("startvalue", models.IntegerField(null=True)),
                ("endx", models.FloatField(null=True)),
                ("endy", models.FloatField(null=True)),
                ("endvalue", models.IntegerField(null=True)),
                ("image", models.ImageField(null=True, upload_to="trainImage/")),
                ("needlemask", models.ImageField(null=True, upload_to="trainMask/")),
                ("needleKD", models.FileField(null=True, upload_to="trainMask/")),
                ("discmask", models.ImageField(null=True, upload_to="trainMask/")),
                ("discKD", models.FileField(null=True, upload_to="trainMask/")),
            ],
        ),
    ]
