# Generated by Django 4.2.5 on 2023-10-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_maskrcnndata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskrcnndata',
            name='discKD',
            field=models.FileField(null=True, upload_to='maskrcnnFile/trainMask/'),
        ),
        migrations.AlterField(
            model_name='maskrcnndata',
            name='discmask',
            field=models.ImageField(null=True, upload_to='maskrcnnFile/trainMask/'),
        ),
        migrations.AlterField(
            model_name='maskrcnndata',
            name='image',
            field=models.ImageField(null=True, upload_to='maskrcnnFile/trainImage/'),
        ),
        migrations.AlterField(
            model_name='maskrcnndata',
            name='needleKD',
            field=models.FileField(null=True, upload_to='maskrcnnFile/trainMask/'),
        ),
        migrations.AlterField(
            model_name='maskrcnndata',
            name='needlemask',
            field=models.ImageField(null=True, upload_to='maskrcnnFile/trainMask/'),
        ),
    ]
